name: CD

permissions:
  contents: write

on:
    workflow_run:
      workflows: ["CI"]
      types:
        - completed

    workflow_dispatch:
      inputs:
        ref:
          description: 'Commit SHA to run the workflow on'
          required: true
          default: 'main'

jobs:
  semrel:
    # Ensure that the CD workflow only triggers when the CI workflow succeeds
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ steps.semrel.outputs.current-version }}
      log: ${{ steps.semrel.outputs.log }}
      next-version: ${{ steps.semrel.outputs.next-version }}
      release-notes: ${{ steps.semrel.outputs.release-notes }}
      version-changed: ${{ steps.semrel.outputs.version-changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run semrel
        id: semrel
        uses: brianbruggeman/semrel@main

  release:
    if: ${{ needs.semrel.outputs.version-changed == 'true' }}
    needs: [semrel]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: brianbruggeman/semrel@main
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ./semrel update
          cargo update
          git add Cargo.toml Cargo.lock
          # Create a nice commit log
          printf "%s\n\n%s\n\n# Log\n%s\n" \
          "${{ needs.semrel.outputs.next-version }}" \
          "$(echo '${{ needs.semrel.outputs.release-notes }}' | base64 --decode)" \
          "$(echo '${{ needs.semrel.outputs.log }}' | base64 --decode)" \
          | git commit -F -
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
      - name: Create Release Notes
        run: printf "%s" "${{ needs.semrel.outputs.release-notes }}" | base64 --decode > release-notes-${{ needs.semrel.outputs.next-version }}.md
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: rand-${{ needs.semrel.outputs.next-version }}
          body_path: release-notes-${{ needs.semrel.outputs.next-version }}.md
          generate_release_notes: false
          make_latest: true
          draft: false
          prerelease: false
          tag_name: ${{ needs.semrel.outputs.next-version }}
          token: ${{ secrets.GITHUB_TOKEN }}